const {
  Theme,
} = require('../../../../javascripts/common/_theme');
const {
  Blue, LightBlue, Purple, utilColors, Yellow, Green,
} = require('../../../../../colors/_colors');

const lightTheme = Theme.light;
const darkTheme = Theme.dark;

const thememaplight = {
  'admin-text-color-1': lightTheme.utilColors.dark,
  'admin-text-color-2': lightTheme.screenYellow.fadedBtnTextColor,
  'admin-text-color-3': lightTheme.screenYellow.btnBg,
  'admin-text-color-4': utilColors.lightGrey,
  'admin-btn-bg': lightTheme.screenYellow.btnBg,
  'admin-body-bg': lightTheme.screenYellow.bodyBg,
  'admin-nav-bg': lightTheme.screenYellow.navBg,
  'admin-nav-active-bg': lightTheme.screenYellow.navActiveBg,
  'admin-hero-nav-games-bg': LightBlue.color300,
  'admin-hero-nav-course-bg': '#6ec399',
  'admin-hero-nav-class-bg': Purple.color300,
  'admin-hero-nav-challenge-bg': Blue.color300,
  'admin-game-card-bg': LightBlue.color50,
  'admin-game-btn-bg': LightBlue.color700,
  'admin-game-progress-gradient-1': Blue.color500,
  'admin-game-progress-gradient-2': LightBlue.color500,
  'admin-exclusive-card-bg': Green.color50,
  'admin-exclusive-title-color': Green.color700,
  'admin-leaderboard-title-bg': Blue.color50,
  'admin-leaderboard-title-text': LightBlue.color900,
  'admin-leaderboard-btn-color': Blue.color900,
  'admin-achievement-title-bg': Yellow.color100,
  'admin-achievement-btn-color': Yellow.color900,
  'admin-club-title-bg': lightTheme.screenGreen.bodyBg,
  'admin-club-btn-color': Green.color900,
  'admin-challenges-arrow-color': Yellow.color900,
  'admin-hero-shadow': '0 4px 16px #f9a82625',
  'price-light-green-bg': '#E5F4ED',
  'price-dark-green-color': '#178958',
};
// just copied the light theme colors to the dark for now
  // TODO: make this a real dark theme with appropriate colors
const thememapdark = {
  'admin-text-color-1': darkTheme.utilColors.dark,
  'admin-text-color-2': darkTheme.screenYellow.fadedBtnTextColor,
  'admin-text-color-3': darkTheme.screenYellow.btnBg,
  'admin-text-color-4': utilColors.lightGrey,
  'admin-btn-bg': darkTheme.screenYellow.btnBg,
  'admin-body-bg': darkTheme.screenYellow.bodyBg,
  'admin-nav-bg': darkTheme.screenYellow.navBg,
  'admin-nav-active-bg': darkTheme.screenYellow.navActiveBg,
  'admin-hero-nav-games-bg': LightBlue.color300,
  'admin-hero-nav-course-bg': '#6ec399',
  'admin-hero-nav-class-bg': Purple.color300,
  'admin-hero-nav-challenge-bg': Blue.color300,
  'admin-game-card-bg': LightBlue.color50,
  'admin-game-btn-bg': LightBlue.color700,
  'admin-game-progress-gradient-1': Blue.color500,
  'admin-game-progress-gradient-2': LightBlue.color500,
  'admin-exclusive-card-bg': Green.color50,
  'admin-exclusive-title-color': Green.color700,
  'admin-leaderboard-title-bg': Blue.color50,
  'admin-leaderboard-title-text': LightBlue.color900,
  'admin-leaderboard-btn-color': Blue.color900,
  'admin-achievement-title-bg': Yellow.color100,
  'admin-achievement-btn-color': Yellow.color900,
  'admin-club-title-bg': lightTheme.screenGreen.bodyBg,
  'admin-club-btn-color': Green.color900,
  'admin-challenges-arrow-color': Yellow.color900,
  'admin-hero-shadow': '0 4px 16px #f9a82625',
  'price-light-green-bg': '#E5F4ED',
  'price-dark-green-color': '#178958',
};

const cssvars = {
  'admin-text-color-1': '--admin-text-color-1',
  'admin-text-color-2': '--admin-text-color-2',
  'admin-text-color-3': '--admin-text-color-3',
  'admin-text-color-4': '--admin-text-color-4',
  'admin-btn-bg': '--admin-btn-bg',
  'admin-body-bg': '--admin-body-bg',
  'admin-nav-bg': '--admin-nav-bg',
  'admin-nav-active-bg': '--admin-nav-active-bg',
  'admin-hero-nav-games-bg': '--admin-hero-nav-games-bg',
  'admin-hero-nav-course-bg': '--admin-hero-nav-course-bg',
  'admin-hero-nav-class-bg': '--admin-hero-nav-class-bg',
  'admin-hero-nav-challenge-bg': '--admin-hero-nav-challenge-bg',
  'admin-game-card-bg': '--admin-game-card-bg',
  'admin-game-btn-bg': '--admin-game-btn-bg',
  'admin-game-progress-gradient-1': '--admin-game-progress-gradient-1',
  'admin-game-progress-gradient-2': '--admin-game-progress-gradient-2',
  'admin-exclusive-card-bg': '--admin-exclusive-card-bg',
  'admin-exclusive-title-color': '--admin-exclusive-title-color',
  'admin-leaderboard-title-bg': '--admin-leaderboard-title-bg',
  'admin-leaderboard-title-text': '--admin-leaderboard-title-text',
  'admin-leaderboard-btn-color': '--admin-leaderboard-btn-color',
  'admin-achievement-title-bg': '--admin-achievement-title-bg',
  'admin-achievement-btn-color': '--admin-achievement-btn-color',
  'admin-club-title-bg': '--admin-club-title-bg',
  'admin-club-btn-color': '--admin-club-btn-color',
  'admin-challenges-arrow-color': '--admin-challenges-arrow-color',
  'admin-hero-shadow': '--admin-hero-shadow',
  'price-light-green-bg': '--price-light-green-bg',
  'price-dark-green-color': '--price-dark-green-color',
};

module.exports = {
  thememapdark,
  thememaplight,
  cssvars,
};
